### ISSUE TITLE
Gnome 3.32 / Ubuntu 19.04 support?

### ISSUE THREAD

**Issue by lydell** [CZ-NIC/run-or-raise#16]
Hi! I like this extension very much.

Would it be possible to update it for Gnome 3.32 / Ubuntu 19.04? Currently, it does not appear to be doing anything on that version.

Maybe I can fix it myself if you have any pointers on where to start.

Thanks!

**Comment by e3rd** [comment]
Awww, it doesn't work with the next version again :D I plan to upgrade to 19.04 soon so I'll debug this when I'm there so I can live. An error could be seen for example via `dmesg` (`/var/log/...`).

**Comment by e3rd** [comment]
Could you try current master here from the repository? With the change I just made it started working.

**Comment by lydell** [comment]
Sure! Except I don’t know how – I’ve never worked on Gnome extensions before.

**Comment by e3rd** [comment]
1. Download this repository a replace files in the `~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/`
2. Restart the shell (tell the system to reload extension files): `<Alt>+<F2>, r, <Enter>`
3. Reload the extension by toggling off and on in `gnome-shell-extension-prefs`
4. Ask if you face another problem :)

(You may restart instead of 2. and 3.)

**Comment by lydell** [comment]
Thanks! Latest master seems to work perfectly! :100:
