### ISSUE TITLE
Prefs window freezes while shortcuts.conf is opened

### ISSUE THREAD

**Issue by freddyhayward** [CZ-NIC/run-or-raise#2]

**Comment by e3rd** [comment]
I was searching for an alternative way of executing commands than  `imports.gi.GLib.spawn_command_line_sync` but I was unsuccessful :( . I've been trying to put `&` on the end of line but in that case, no editor was opened. Since there is quite a bad documentation of extending GNOME3, I don't know how to solve that issue.

In every case, you may edit shortcuts.conf directly in your `/home/...gnome-shell/extensions/run-or-raise@edvard.cz`

**Comment by e3rd** [comment]
Does not occur anymore in Ubuntu 20.10 (and `kate` being the default editor)
