### ISSUE TITLE
Auto-update seems to have broken the extension

### ISSUE THREAD

**Issue by karottenreibe** [CZ-NIC/run-or-raise#31]
I noticed today that the extension no longer works. It seems to have auto-updated to version 7 and then it got disabled in the process:

![image](https://user-images.githubusercontent.com/38839/110922802-6e70a400-8320-11eb-9cb4-7b1a6d7a63c0.png)

When I look at the extension website https://extensions.gnome.org/extension/1336/run-or-raise/ I see this:

![image](https://user-images.githubusercontent.com/38839/110922851-7fb9b080-8320-11eb-8f15-c2c07a39e5b8.png)

There's no further information about the supposed "ERROR" and that thing is not clickable. I can open the extension settings just fine but no error is shown there either.

Uninstalling and reinstalling ends in the same "ERROR" state with no additional error message shown anywhere.

**Comment by e3rd** [comment]
Thanks for posting the report. 

* What is your system version and gnome version (Settings / About)?
![image](https://user-images.githubusercontent.com/6942231/110927997-a7ac1280-8326-11eb-835f-d9319a75d4d1.png)

* Is anything written in the /var/log/syslog ?

**Comment by karottenreibe** [comment]
Thanks, /var/log/syslog shows:

```
Mar 12 10:45:44 k gnome-shell[2262]: JS ERROR: Extension run-or-raise@edvard.cz: SyntaxError: fields are not curren
tly supported @ /home/k/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:52
```

Seems unrelated to #30 

My system is Ubuntu 20.04.2
Gnome 3.36.8

**Comment by e3rd** [comment]
Will you try that, please? I've commented the line 52 because it's just an explicit declaration of a static variable while explicitly declaring might not yet be possible in an older version of JavaScript.

* Rename the file to `extension.js` (strip the `.txt`)
* Replace the file at `~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js`
* Restart the shell <kbd>Alt+F2 + r</kbd>

[extension.js.txt](https://github.com/CZ-NIC/run-or-raise/files/6129990/extension.js.txt)

**Comment by karottenreibe** [comment]
Now I get this in syslog:

```
Mar 12 20:01:49 k gnome-shell[2181]: JS ERROR: Extension run-or-raise@edvard.cz: SyntaxError: invalid regexp group @ /home/k/.local/
share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:1
```

**Comment by dmocek** [comment]
I have the same issue running Ubuntu 20.04.1 and GNOME 3.36.4.

**Comment by e3rd** [comment]
> I've tried many versions

@dmocek This is really strange to me since this is a new bug and there is no reason versions prior to Feb should not work. Would you be so kind and investigate it further?

> invalid regexp group @

@karottenreibe Since there is no regexp on line 1, I bet there is an error elsewhere. Will you give it a try once more, restore the original master version, check that it raises the original error `SyntaxError: fields are not curren ... extension.js:52` and then manually comment the incriminated line 52? I'd be very grateful!

```js
class Accelerator extends Array {

    /**
     * @type {Map}
     */
    static grabbers
...
```

Change to

```js
class Accelerator extends Array {

    // static grabbers
```

**Comment by karottenreibe** [comment]
I did so:

- put current master version into extension.js
- reload -> original error about fields not being supported
- comment out the static field
- reload -> error about regex

no change in behaviour

**Comment by karottenreibe** [comment]
I tried changing all regexes in the file and I at least get a different error when I change the one in line 530:

```js
            .map((m) => m.match(/(?<key>[^(]*)(\((?<arg>.*?)\))?/)) // "launch" -> key=launch, arg=undefined
```

Maybe that one is causing the problem?

**Comment by karottenreibe** [comment]
Maybe the ?<name> named capture groups aren't supported by the Gnome 3.36 JS engine yet?

**Comment by karottenreibe** [comment]
Oh and sorry, I forgot to mention: when I replace that regex in line 530 with just `/a/` the shortcuts work again, so I very much suspect that's the problematic line :-)

**Comment by zba** [comment]
same here, will check later if have time,

**Comment by zba** [comment]
I installed version 6 for gnome 38.1 , works for now.

@e3rd I think you used too-advanced syntax in new version, many things not works
- static props
- named groups in regex
-  ```reference to undefined property "gettext-domain"```  (when click edit)

**Comment by e3rd** [comment]
The solution might be to flag this version as compatible with Gnome 3.38+ only. But since this is a major update, I'd prefer its features would be available in Ubuntu 20.04.

> named groups

You must be right, I'll cancel the named groups.

> line 530

It's strange you have it at 530, I have it at 511: https://github.com/CZ-NIC/run-or-raise/blob/3316e88718e145ca6185648904047b4afded1bae/extension.js#L511

> reference to undefined property "gettext-domain" (when click edit)

@zba What do you mean be clicking edit please?

**Comment by e3rd** [comment]
I've pushed a new commit that removes named groups and the static attribute. Would you mind checking if that version works? https://github.com/CZ-NIC/run-or-raise/blob/master/extension.js

> reference to undefined property "gettext-domain" (when click edit)

@zba What do you mean be clicking edit please? I might need to correct this too before pushing publicly to the https://extensions.gnome.org/

**Comment by dmocek** [comment]
I get this error now:

3286 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Could not load extension run-or-raise@edvard.cz_original-dir-name: Error: Missing metadata.json#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:281:19#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:34#0
3287 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Could not load extension run-or-raise@edvard.cz2: Error: uuid "run-or-raise@edvard.cz" from metadata.json does not match directory name "run-or-raise@edvard.cz2"#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:306:19#012_loadExten
3288 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Extension run-or-raise@edvard.cz: Error: Argument 'display' (type interface) may not be null#012@/home/dmocek/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:8:27#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.j
3289 Mar 15 09:37:35 localhost gnome-shell[56818]: JS WARNING: [/home/dmocek/.local/share/gnome-shell/extensions/status-area-horizontal-spacing@mathematical.coffee.gmail.com/convenience.js 19]: reference to undefined property "gettext-domain"
3290 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Could not load extension ubuntu-dock@ubuntu.com: Error: Missing metadata.json#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:281:19#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:34#012collectFromDatad

**Comment by zba** [comment]
> The solution might be to flag this version as 
> @zba What do you mean be clicking edit please?

In settings, edit config file, if i click, it not works and logs this message.

**Comment by karottenreibe** [comment]
> I've pushed a new commit that removes named groups and the static attribute. Would you mind checking if that version works? https://github.com/CZ-NIC/run-or-raise/blob/master/extension.js
> 

That makes the shortcuts work for me again :-)

**Comment by e3rd** [comment]
> @zba browserlist support, for gnome-shell

What do you mean, please? Browsers like Firefox? What should be the usecase?

> reference to undefined property "gettext-domain"

Although that both @zba and @dmocek report the same `reference to undefined property "gettext-domain"`, I suspect, we handle two different errors here.

# @zba report

Would you please share the full log, not the message only? I need more information to get the idea.

# @dmocek report

This line talks about `run-or-raise@edvard.cz_original-dir-name`

```
3286 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Could not load extension run-or-raise@edvard.cz_original-dir-name: Error: Missing metadata.json#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:281:19#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:34#0
```

This line talks about `run-or-raise@edvard.cz2` and `run-or-raise@edvard.cz`. I suspect you've updated the extension.js in run-or-raise@edvard.cz2 but did not update its metadata.json accordingly or something like that.

```
3287 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Could not load extension run-or-raise@edvard.cz2: Error: uuid "run-or-raise@edvard.cz" from metadata.json does not match directory name "run-or-raise@edvard.cz2"#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:306:19#012_loadExten
```

This line talks about the original `run-or-raise@edvard.cz` name but raises the error: `Argument 'display' (type interface) may not be null`. Which is the same error as in #30 . The reporter @jdeut claimed that the culprit was not run-or-raise extension. If it still raises this error, would you open a new issue (informing about having Wayland or X11 session, Ubuntu and Gnome Shell version).


```
3288 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Extension run-or-raise@edvard.cz: Error: Argument 'display' (type interface) may not be null#12@/home/dmocek/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:8:27#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.j
```

These lines refers `reference to undefined property "gettext-domain"` but concerns **another** extension whose name is `status-area-horizontal-spacing@mathematical.coffee.gmail.com` and ubuntu-dock@ubuntu.com

```
3289 Mar 15 09:37:35 localhost gnome-shell[56818]: JS WARNING: [/home/dmocek/.local/share/gnome-shell/extensions/status-area-horizontal-spacing@mathematical.coffee.gmail.com/convenience.js 19]: reference to undefined property "gettext-domain"
3290 Mar 15 09:37:35 localhost gnome-shell[56818]: JS ERROR: Could not load extension ubuntu-dock@ubuntu.com: Error: Missing metadata.json#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:281:19#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:34#012collectFromDatad
```

**Comment by dmocek** [comment]
@e3rd 
- Where can I send the log?  It's 1.8M.  I'd rather send it in private if possible.
- I've tried several versions and it's not clear to me which one I should be using for Ubuntu 20.04.1 and GNOME 3.36.4.  Start with v7 and use your extension.js?

Thanks

**Comment by e3rd** [comment]
> Start with v7 and use your extension.js modification?

Yes! :) 

> Where can I send the log?

Only lines concerning run-or-raise are sufficient (ex grep run-or-raise). Or use https://www.file.io/ or anything you want :)

**Comment by dmocek** [comment]
OK.  It's working for me now.  It turns out I had a bad copy of your latest extension.js that was adding to the problems.

What can we do to mitigate the breaking of r-o-r?  It's vital to the way I work (thanks for working on this btw).  It has broken on me several times due to updates.

**Comment by dmocek** [comment]
@e3rd...here is more information.  I have another Ubuntu 20.04 machine at home.  This one is running Ubuntu 20.04.2 LTS and GNOME v3.36.8 on Wayland.  With v7 and the latest extension.js updated (like my other machine), r-o-r does not work and I am getting this error:

Mar 15 22:17:00 gp18 gnome-shell[5772]: JS ERROR: Extension run-or-raise@edvard.cz: Error: Argument 'display' (type interface) may not be null#012@/home/dmocek/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz/extension.js:8:27#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:425:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:346:27#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22#012start@resource:///org/gnome/shell/ui/main.js:146:5#012@<main>:1:47

**Comment by e3rd** [comment]
Can you go to the Alt+F2 `lg` and run `imports.gi.Gdk.Keymap.get_default()` ? If the output is `[object instance ... whatever` we've won and I might know how to solve the issue.

> What can we do to mitigate the breaking of r-o-r?

Apart submitting issue here you can always return to a [previously used](https://extensions.gnome.org/extension/1336/run-or-raise/) version – just choose the shell version and the version number.

**Comment by dmocek** [comment]
Yes, the output is: [object instance wrapper GType:GdkX11Keymap jsobj@0x25ed87eb2460 native@0x560681198490]

**Comment by dmocek** [comment]
BTW, can't the JavaScript be written such that it tests for a version of GNOME and/or JS and/or JS functionality and does the right thing based on that?  This way there can be a single script that covers a wider range and might be able to do the right thing if things change underneath.  Not sure of the performance hit of doing this.

**Comment by e3rd** [comment]
Please note that I'm not a fully time Gnome developer. I've passed many hours, diving into the majestic labyrinth of the terms like gnome-shell, gjs, mutter, clutter, glib, gio, gtk, gdk, gobject, gi and gdm. Give me the right documentation and I may do it. Manuals that exist often fails for not reflect the rapid development of the Gnome world – the API changes. For now, I am not able to guess what version of whatever should correspond to a functionality.

**Comment by e3rd** [comment]
I've submitted the version solving the initial issue to the Gnome developers to review. If anyone of you have additional comment, I'd be glad if you report the here or to the new issue. Thanks for the cooperation.

**Comment by dmocek** [comment]
@e3rd, re: not a full time Gnome developer...I understand and *really* appreciate the work you've done on this and your responsiveness when things go wrong.  As I said previously, I use your extension a great deal and it's built into my muscle memory to the point where it disrupts my productivity when it's not working.

I will do some digging and see if there's a way to make it more resilient to GNOME changes.

**Comment by e3rd** [comment]
Thanks and I understand the frustration that a vital tool stops working like that. I remember you helped me a lot in the past. I hope reverting to an old version at Gnome extension homepage will always work in case of a future error. This change was a big one I wanted to backport to the LTS versions and it's a pity that API changed meanwhile. (Some developer told me I should use Clutter instead of GDK which is good I did not find a GDK javascript source code, only its C-bindings.)

Have a nice day.
