### ISSUE TITLE
PCManFM not raised, but Dolphin is

### ISSUE THREAD

**Issue by humanplayer2** [CZ-NIC/run-or-raise#47]
PCManFM and Dolphin both have the nice feature that they open new tabs in the existing window when you send them a command to open a directory. 

However, they behave differently under Run or Raise. Dolphin behaves as I would expect. Using

    <Super>a:move-window-to-active-workspace:minimize-when-unfocused,dolphin,dolphin,
    <Super>b:move-window-to-active-workspace,dolphin ~/Downloads,dolphin,Downloads,

`<Super>a` raises and lowers Dolphin, and `<Super>b` opens a new tab at Downloads and brings the window to the foreground on the current workspace. Great!

But not so for PCManFM.
 
    <Super>c:move-window-to-active-workspace:minimize-when-unfocused,pcmanfm,Pcmanfm,
    <Super>d:move-window-to-active-workspace,pcmanfm ~/Downloads,Pcmanfm,Downloads,

Here, `<Super>c` works as intended, but `<Super>d` does not: if PCManFM is *not* focused on a Downloads tab, then the tab will be opened and I get a notification that my window is ready, but it is not moved to the current workspace, nor is it raised on the workspace it is on.  (If a Downloads tab is focused, the window will be raised/brought to the current workspace).

Using `<Super>d , <Super>c`  does the intended, but I would be nice to not have to do the `<Super>c`.

Can you suggest me a hack to get PCManFM to behave?

**Comment by e3rd** [comment]
(sorry I won't have time to look to this issue this week :( )

**Comment by e3rd** [comment]
Unfortunately I have bad news for you. As run-or-raise works with windows, it has no clue what's happenning in the application. The tabs the application manages are internal.

In your case both wm_class and title are set, so both must match. If you're on the Downloads tab in an application, it is found and raised to the active workspace. However, when you're on the different tab, launch command is triggered and two things happen.

* `dolphin ~/Downloads` → dolphin moves to the active workspace (but no due to run-or-raise but because dolphin). However, tab with the Download folder is not the chosen one.
* `pcmanfm ~/Downloads` → pcmanfm opens a new tab with Download and does not choose to change the workspace

So this has something to do with the will of the applications. You have many different options to cope with that. (My way is to use Krusader and Ctrl+D to change bookmarked directories.)

**Comment by humanplayer2** [comment]
Ah. Well, I'm glad all with the extensions is in order. I appreciate both the explanation, and the tips. Thank you for those!
