### ISSUE TITLE
Feature request: Add the ability for Run or Raise to be trigger by terminal scripts

### ISSUE THREAD

**Issue by thebunnyrules** [CZ-NIC/run-or-raise#8]
Run or raise is one of the first extensions or apps that I've seen in gnome-wayland that gives the user the ability to raise windows. I can't even get gedit to raise when new tabs are opened at the moment, so the fact that an extension has the feature is pretty amazing.

I was wondering if it would be possible to add additional ways of triggering the run or raise behavior than hotkeys. It would be nice if we can set it up so that it can be trigger by scripts. For example, the extension can maybe poll for the existence of a certain file that the script can create and inside the file, there would be a raise command of some sort that the extension would execute.

**Comment by e3rd** [comment]
Wow, I've never thought about replacing something like wmctrl!  
Could you describe a usecase so that I grasp it better, please? :)

**Comment by thebunnyrules** [comment]
Sure no problem. The first thing I would do with it, is make a script that would replace the gedit exectuable. For example, gedit-rase. The script can be set as the default app to text files, js, xml etc. (the things usually opened by gedit). When I run gedit-raise, it would use ps ax to check if gedit is opened already. if it is, it would write a file say: /tmp/raiseme, and put in some arbitrary command like: raise gedit for example, and run or raise would raise a window with gedit in it's name or just raise the gedit process. as soon as it executes the command, it deletes the file.

**Comment by e3rd** [comment]
Concerning gedit, on my system it gets focus every time a new file is open. Independent if being opened from Nautilus, Krusader od a terminal.

I had an idea once to expose the functionality through a port to localhost so that other applications could do what they need. But unfortunately, I'm little familiar with the gnome-shell too and I haven't studied enough to decide if that wouldn't be against a Wayland security principles or if that should be a completely different plugin than run-or-raise. Either way, it's a lot of work to do and since the development is extensivelly challenging – logout after each change makes you a tough time – I fear not to be able to schedule this feature.

**Comment by thebunnyrules** [comment]
I can totally understand your desire to want to understand Wayland's security principles further before implementing any new functions. Not necessarilly related to my idea but just as a general advice, if you have an idea but are not sure what it's security implications are going to be, you can always get on the gnome and wayland mailing lists and bounce your ideas off of them. 

I'm not very well versed in JS synthax. I'll be learning it in the next few months and maybe I'll take up my idea, code it and propose it as commit or maybe I'll just do a fork. It seems to me that you've already done the most difficult thing - extension iniated raising. I personally wouldn't have been able to figure out that part as a beginner extension writer but the rest of my idea, it's just standard js. It involves modifying your extension a little: instead of hotkeys, do a loop that checks for the existence of a certain temp file every 0.5 secs in a preset dir, see if the file has any commands that extension recognizes, compare commands against an user generated list of permissions that's either put in a root owned dir or the user has set it as read only (chattr +i, which can only be undone/done as root).

 Also, I've not been able to get any non-gtk native app to run native wayland in gnome-shell wayland. For example, even though I have all the plasma wayland files installed, dolphin/kdiff/kate/kwrite will only run in native x mode on my gnome-shell wayland (even though all these have native wayland support when running kde plasma wayland). Are you able to get krusader to run natively in wayland (are you sure it's not running in a X11 emulation layer and launching gedit in x11)? you can test if an app is running native wayland by going to terminal and entering: xeyes. It's a little X11 widget which puts a pair of eyes on your monitor that follow your cursor. This widget only works in X11 and not in wayland. Meaning, eyes will follow your mouse when you mouse over a X11 native app (like firefox or gimp) but will no longer be able to track your mouse when you mouse over a wayland native app: like gnome-terminal in a wayland sessions. It would be fun to know if your Krusader is running under X and whether the gedit instance it launches is running under wayland or X.

**Comment by e3rd** [comment]
Hello, sorry for late reply. 
* I run Ubuntu 19.04
* Program `xeyes` works and this return x11.
```bash
$ loginctl show-session $(loginctl|grep $(whoami) |awk '{print $1}') -p Type
Type=x11
```

* It seems to me a better idea to investigate why raising does not work for you instead of setting up a whole file checking & grammar language that would simulate similar behaviour. But maybe I got you wrong.
* Maybe your obstacles could be solved by [Focus my window](https://extensions.gnome.org/extension/1005/focus-my-window/) extension (I'm just guessing.)

Please let me know if you still experiencing the issues or if have it disappeared with the new Ubuntu release and we may re-open this issue.
